package com.bosha.vault;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;
import javax.imageio.ImageIO;
import com.google.zxing.*;
import com.google.zxing.common.BitMatrix;

/** Exercises the app's actual decoder with QR PNGs generated by the Windows/core renderer. */
public final class QrInteropTest {
    private static int checks;
    private static void check(boolean condition,String name){if(!condition)throw new AssertionError(name);checks++;System.out.println("PASS "+name);}
    private static byte[] luma(BufferedImage image){byte[] pixels=new byte[image.getWidth()*image.getHeight()];for(int y=0;y<image.getHeight();y++)for(int x=0;x<image.getWidth();x++){int rgb=image.getRGB(x,y);pixels[y*image.getWidth()+x]=(byte)((((rgb>>16)&255)*299+((rgb>>8)&255)*587+(rgb&255)*114)/1000);}return pixels;}
    private static String decode(BufferedImage image){return PairingQrDecoder.decode(luma(image),image.getWidth(),image.getHeight());}
    private static BufferedImage cameraFrame(BufferedImage qr,boolean rotated){BufferedImage frame=new BufferedImage(1280,720,BufferedImage.TYPE_INT_RGB);Graphics2D g=frame.createGraphics();g.setColor(new Color(176,179,191));g.fillRect(0,0,1280,720);g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);if(rotated){g.translate(640,360);g.rotate(Math.PI/2);g.drawImage(qr,-155,-155,310,310,null);}else g.drawImage(qr,485,205,310,310,null);g.dispose();return frame;}
    private static BufferedImage qr(String text)throws Exception{BitMatrix bits=new MultiFormatWriter().encode(text,BarcodeFormat.QR_CODE,380,380);BufferedImage image=new BufferedImage(380,380,BufferedImage.TYPE_INT_RGB);for(int y=0;y<380;y++)for(int x=0;x<380;x++)image.setRGB(x,y,bits.get(x,y)?0xff000000:0xffffffff);return image;}
    private static boolean rejected(String code){try{new LocalTransfer(code);return false;}catch(Exception expected){return true;}}
    public static void main(String[] args)throws Exception {
        Path folder=Paths.get(args[0]);
        for(String host:new String[]{"192.168.1.24","10.42.0.1","172.31.255.254"}){
            String expected=new String(Files.readAllBytes(folder.resolve(host+".txt")),java.nio.charset.StandardCharsets.UTF_8);
            BufferedImage png=ImageIO.read(folder.resolve(host+".png").toFile());
            check(expected.equals(decode(png)),"Windows QR → Android decoder exact payload: "+host);
            new LocalTransfer(decode(png));check(true,"Decoded QR passes private pairing validation: "+host);
            check(expected.equals(decode(cameraFrame(png,false))),"310px display captured in 1280x720 frame: "+host);
            check(expected.equals(decode(cameraFrame(png,true))),"Rotated camera frame: "+host);
        }
        String url="https://example.com/untrusted";String read=decode(qr(url));check(url.equals(read)&&rejected(read),"Unrelated URL QR is rejected before connecting");
        String raw="{\"v\":1,\"host\":\"8.8.8.8\",\"port\":45678,\"cert\":\""+String.join("",Collections.nCopies(64,"a"))+"\",\"token\":\""+Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32])+"\"}";
        String publicCode="BV1:"+Base64.getUrlEncoder().withoutPadding().encodeToString(raw.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        check(rejected(decode(qr(publicCode))),"Public-IP pairing QR is rejected before connecting");
        check(PairingQrDecoder.decode(new byte[1],1280,720)==null,"Truncated preview frame is refused");
        check(PairingQrDecoder.decode(new byte[1],Integer.MAX_VALUE,Integer.MAX_VALUE)==null,"Oversized frame dimensions are refused without overflow");
        BufferedImage blank=new BufferedImage(640,480,BufferedImage.TYPE_INT_RGB);check(decode(blank)==null,"A frame with no QR is ignored");
        System.out.println(checks+" QR interoperability and validation checks passed.");
    }
}
